from pictures.service.aip_service import aip_service
from pictures.service.recognize_service import RecognizeService
from pictures.service.weibo_crawler import WeiboCrawler
from pictures.service.hello_homepage import HelloProjectHomePageCrawler
