version: "2.3"

services:
  mysql:
    image: mysql:5.7.37
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /data/mysql/data:/var/lib/mysql
      - /data/mysql/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: auPr^qf7ePY0
  redis:
    image: redis:6.2.6
    container_name: redis
    restart: always
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - /data/redis/conf:/usr/local/etc/redis
      - /data/redis/data:/data